version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports: 
    - "8086:8086"
    environment:
     - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
     - INFLUXDB_DATA_INDEX_VERSION=tsi1
    volumes:
    - D:\Learnings\InfluxDb-Learn\dbdata\influxdb:/var/lib/influxdb
    - D:\Learnings\InfluxDb-Learn\dbdata\influxdb.conf:/etc/influxdb/influxdb.conf:ro
    # entrypoint: ["influxdb", "-config", "/etc/influxdb/influxdb.conf"]
    networks:
    - influx-stack

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports: 
    - "8888:8888"
    environment:
     - INFLUXDB_URL=http://influxdb:8086
    volumes:
    - D:\Projects\Learning\InfluxDb-Learn\dbdata\chronograf:/var/lib/chronograf
    networks:
    - influx-stack

    # --------------------------------------------- #
networks:
  influx-stack:
    name: influx-stack
    driver: bridge